# -*- coding: utf-8 -*-
"""ScarMaxwellAssignment6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ybeGIyPwtI_yzXWJfpFfvIM_qxpf00Fi
"""

### Scar Maxwell 2/3/24

print("""The purpose of this program is to display population growth of
a city for 50 years if the growth rate were to stay constant.""")

## Declaring variables
year = 1
growth = 0
curPop = 0
city = input("Please enter the name of the city: ")
pop = input("Please enter the current population of the city: ")
rate = input("Please enter the growth rate of your city: ")
firstPop = pop

## Changing variable data types
curPop = int(curPop) # Changes the variable from string data type to integer data type.
rate = int(rate) # Changes the variable from string data type to integer data type.
firstPop = float(firstPop) # Changes the variable from a string data to float data type.
pop = float(pop)

rate /= 100 # Turns the rate entered by the user into a decimal so it can function as a rate.

## "population loop" Loop to calculate the population change over 50 years
while year <= 50: # Stops the loop at 50 iterations
  growth = pop * rate # This is the amount of new people per year
  curPop = pop + growth # This is the amount of new people per year added to the current population
  print("Year: {:.0f} Population: {:.0f} Growth: {:.2f} New Pop: {:.0f}".format(year, pop, growth, curPop)) # Prints the year, current population, new people from rate, and new population afer new people added.
  year += 1 # Increase the iteration by 1
  pop = curPop # Changes the current population to the new accumulated population before next loop.

## If...then statement to determine if the population increased or decreased in our population loop to print proper end statements
if firstPop < pop :
  popChange = pop - firstPop
  print("{}'s population grew from {:.0f} to {:.0f} people in 50 years. That's an increase of {:.0f} people!".format(city,firstPop, pop, popChange))
elif firstPop > pop :
  popChange = firstPop - pop
  print("{}'s population decreased from {:.0f} people to {:.0f} people in 50 years. That was a decrease of {:.0f} people!".format(city, firstPop, pop, popChange))
elif firstPop == pop :
  print("There was zero change in population over the 50 year period.")
else :
  print("There must have been an error. Please restart the program.")